def line():
import math
A=float(input ("Ingrese el coeficiente de A:"))
B=float(input ("ingrese el coeficinete B:"))
X1=float(input ("ingrese el coeficiente X1:"))
X2=float(input ("ingrese el coeficiente X2:"))
print("El coeficiente A de su ecuacion de la recta es:",A)
print("El coeficiente B de su ecuacion de la recta es:",(B))
print("El coeficiente X1 de su ecuacion de la recta es:",(X1))
print("El coeficiente B de su ecuacion de la recta es:",(X2))
print("")
print("dados los siguientes puntos:")
Y1=(A)*(X1)+(B)
Y2=(A)*(X2)+(B)
print("\tP1("+str((X1))+ " " ,str(Y1)+")")
print("\tP1("+str((X2))+ " " ,str(Y2)+")")
print("")
distancia=(((X2-21)**2)+((Y2-Y1)**2))**(1/2)
print("La distancia entre ellos es:", distancia)
